trigger:
- main

pool:
  name : ABC

variables:
  imageRepository: 'productcatalogue'
  kubernetesNamespace: 'monitoring'
  containerRegistry: 'javaemo.azurecr.io'
  tag: '$(Build.BuildId)'
  aksClusterName: 'rg-aks-dev'
  aksResourceGroup: 'demo'
  azureServiceConnection: 'aks-dev-service-connection'
  acrServiceConnection: 'acr-service-connection'

steps:

# -----------------------------
# Step 1: Maven Build
# -----------------------------
- task: Maven@3
  displayName: 'Build productcatalogue JAR'
  inputs:
    mavenPomFile: 'productcatalogue/pom.xml'
    goals: 'clean package'

# -----------------------------
# Step 2: Docker Build & Push to ACR
# -----------------------------
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: $(acrServiceConnection)
    repository: $(imageRepository)
    command: buildAndPush
    Dockerfile: productcatalogue/Dockerfile
    buildContext: productcatalogue
    tags: |
      $(tag)

# -----------------------------
# Step 3: Get AKS Credentials
# -----------------------------
- task: AzureCLI@2
  displayName: 'Get AKS Credentials'
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az aks get-credentials \
        --resource-group $(aksResourceGroup) \
        --name $(aksClusterName) \
        --overwrite-existing

      kubectl get nodes

# -----------------------------
# Step 4: Update Image Tag in Manifests
# -----------------------------
- bash: |
    sed -i "s#REPLACE_IMAGE#$(containerRegistry)/$(imageRepository):$(tag)#g" productcatalogue/k8s/deployment.yaml
    sed -i "s#REPLACE_IMAGE#$(containerRegistry)/$(imageRepository):$(tag)#g" productcatalogue/k8s/daemonset.yaml

    echo "Updated deployment.yaml"
    cat productcatalogue/k8s/deployment.yaml
  displayName: 'Update Kubernetes Manifests'

# -----------------------------
# Step 5: Deploy to AKS
# -----------------------------
- bash: |
    kubectl apply -n $(kubernetesNamespace) -f productcatalogue/k8s/deployment.yaml
    kubectl apply -n $(kubernetesNamespace) -f productcatalogue/k8s/service.yaml
    kubectl apply -n $(kubernetesNamespace) -f productcatalogue/k8s/daemonset.yaml
    kubectl apply -n $(kubernetesNamespace) -f productcatalogue/k8s/node-exporter-service.yaml
    kubectl apply -n $(kubernetesNamespace) -f productcatalogue/k8s/prometheus-config.yaml
    kubectl apply -n $(kubernetesNamespace) -f productcatalogue/k8s/prometheus-deployment.yaml
    kubectl apply -n $(kubernetesNamespace) -f productcatalogue/k8s/grafana.yaml

    kubectl rollout status deployment/productcatalogue -n $(kubernetesNamespace)
  displayName: 'Deploy Application to AKS'
